services:
  kafka:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9095:9095" # added for jmx
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,JMX://0.0.0.0:9095"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker:9092,CONTROLLER://broker:9093,JMX://0.0.0.0:9095"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,JMX:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_NUM_PARTITIONS: "3"
      KAFKA_OPTS: "-javaagent:/jmx/jmx_prometheus_javaagent-1.2.0.jar=9151:/jmx/jmx-config.yaml"
    volumes:
      - ./jmx:/jmx
      - ./create-topics.sh:/create-topics.sh # script added
    entrypoint: ["/bin/sh", "-c", "/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties"] # entrypoint changed
    # Prometheus settings
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka
    network_mode: "bridge"