rules:
  - pattern: kafka.server<type=(.+), name=(.+), topic=(.+)><>Value
    name: kafka_server_$1_$2
    labels:
      topic: "$3"
  - pattern: kafka.consumer<type=(.+), name=(.+), client-id=(.+)><>Value
    name: kafka_consumer_$1_$2
    labels:
      client_id: "$3"
  - pattern: kafka.producer<type=(.+), name=(.+), client-id=(.+)><>Value
    name: kafka_producer_$1_$2
    labels:
      client_id: "$3"

















